server:
   port: 8200
   servlet:
      context-path: /api

spring:
   datasource: 
      url: jdbc:postgresql://localhost:5432/db_school
      username: postgres
      password: 123456
      
   jpa:
      show-sql: true
      properties:
         hibernate:
            format_sql: true
